org: juanrodo
service: api-usuario

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_USER: ${sls:stage}-t_usuario
    TABLE_TOKEN: ${sls:stage}-t_token
    TABLE_ORG: ${sls:stage}-t_org
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

functions:
  crear:
    handler: Lambda_CrearUsuario.lambda_handler
    events:
      - http:
          path: /usuario/crear
          method: post
          cors: true
          integration: lambda
  login:
    handler: Lambda_LoginUsuario.lambda_handler
    events:
      - http:
          path: /usuario/login
          method: post
          cors: true
          integration: lambda

  logout:
    handler: Lambda_Logout.lambda_handler
    events:
      - http:
          path: /usuario/logout
          method: post
          cors: true
          integration: lambda

  validar:
    handler: Lambda_ValidarTokenAcceso.lambda_handler
    events:
      - http:
          path: /usuario/validar
          method: post
          cors: true
          integration: lambda

  listar:
    handler: Lambda_ListarUsuario.lambda_handler
    events:
      - http:
          path: /usuario/listar
          method: get
          cors: true
          integration: lambda

  crearorg:
    handler: Lambda_CrearOrganizacion.lambda_handler
    events:
      - http:
          path: /org/crear
          method: post
          cors: true
          integration: lambda
          
resources:
  Resources:
    TablaUsuarios:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_usuario
        AttributeDefinitions:
          - AttributeName: tenant_id_rol
            AttributeType: S
          - AttributeName: dni
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_rol
            KeyType: HASH
          - AttributeName: dni
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    TablaTokens:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_token
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: token
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: token
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
    TablaOrg:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_org
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
