org: juanrodo
service: api-horario

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    FUNCION_CURSO: api-curso-${sls:stage}-obtenerCurso
    TABLE_HORARIO: ${sls:stage}-t_horario
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

functions:
  crearHorario:
    handler: Lambda_CrearHorario.handler
    events:
      - http:
          path: /horario/crear
          method: post
          cors: true

  listarHorario:
    handler: Lambda_ListarHorario.handler
    events:
      - http:
          path: /horario/listar
          method: get
          cors: true

  obtenerHorario:
    handler: Lambda_BuscarHorario.handler
    events:
      - http:
          path: /horario/buscar
          method: get
          cors: true

  actualizarHorario:
    handler: Lambda_ModiHorario.handler
    events:
      - http:
          path: /horario/modificar
          method: put
          cors: true

  eliminarHorario:
    handler: Lambda_EliminarHorario.handler
    events:
      - http:
          path: /horario/eliminar
          method: delete
          cors: true

  doc:
    handler: Lambda_Doc.handler
    events:
      - http:
          path: /doc
          method: get
          cors: true
      - http:
          path: /doc/{proxy+}
          method: get
          cors: true

resources:
  Resources:
    TablaHorario:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_horario
        AttributeDefinitions:
          - AttributeName: tenant_id_curso_id
            AttributeType: S
          - AttributeName: horario_id
            AttributeType: S
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_curso_id
            KeyType: HASH
          - AttributeName: horario_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_horario_index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: horario_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

package:
  individually: false
  include:
    - doc/**
    - '**/*.js'
