org: juanrodo
service: api-horario

plugins:
  - serverless-openapi-documenter

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 60
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    FUNCION_CURSO: api-curso-${sls:stage}-obtenerCurso
    TABLE_HORARIO: ${sls:stage}-t_horario
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

functions:
  crearHorario:
    handler: Lambda_CrearHorario.handler
    events:
      - http:
          path: /horario/crear
          method: post
          cors: true

  listarHorario:
    handler: Lambda_ListarHorario.handler
    events:
      - http:
          path: /horario/listar
          method: get
          cors: true

  obtenerHorario:
    handler: Lambda_BuscarHorario.handler
    events:
      - http:
          path: /horario/buscar
          method: get
          cors: true

  actualizarHorario:
    handler: Lambda_ModiHorario.handler
    events:
      - http:
          path: /horario/modificar
          method: put
          cors: true

  eliminarHorario:
    handler: Lambda_EliminarHorario.handler
    events:
      - http:
          path: /horario/eliminar
          method: delete
          cors: true

custom:
  openapi:
    title: API de Horarios
    version: 1.0.0
    description: Endpoints para gestión de horarios de cursos: crear, listar, modificar y eliminar.
    output: openapi.json
    format: json
    openApiVersion: 3.0.3
    postmanCollection: postman-horarios.json

    paths:
      /horario/crear:
        post:
          summary: Crear horario
          description: Crea un horario para un curso dado.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CrearHorarioRequest'
          responses:
            '200':
              description: Horario creado exitosamente

      /horario/listar:
        get:
          summary: Listar horarios
          description: Lista todos los horarios disponibles.
          responses:
            '200':
              description: Lista de horarios
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ListarHorariosResponse'

      /horario/buscar:
        get:
          summary: Obtener horario
          description: Obtiene los detalles de un horario específico por ID.
          responses:
            '200':
              description: Horario encontrado
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/HorarioResponse'

      /horario/modificar:
        put:
          summary: Modificar horario
          description: Modifica los detalles de un horario existente.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ActualizarHorarioRequest'
          responses:
            '200':
              description: Horario actualizado correctamente

      /horario/eliminar:
        delete:
          summary: Eliminar horario
          description: Elimina un horario específico.
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/EliminarHorarioRequest'
          responses:
            '200':
              description: Horario eliminado exitosamente

    components:
      schemas:
        CrearHorarioRequest:
          type: object
          required: [tenant_id, curso_id, dias, inicio_hora, fin_hora]
          properties:
            tenant_id:
              type: string
            curso_id:
              type: string
            dias:
              type: array
              items:
                type: string
            inicio_hora:
              type: string
              example: "08:00"
            fin_hora:
              type: string
              example: "10:00"

        ActualizarHorarioRequest:
          type: object
          required: [tenant_id, horario_id, dias, inicio_hora, fin_hora]
          properties:
            tenant_id:
              type: string
            horario_id:
              type: string
            dias:
              type: array
              items:
                type: string
            inicio_hora:
              type: string
              example: "09:00"
            fin_hora:
              type: string
              example: "11:00"

        EliminarHorarioRequest:
          type: object
          required: [tenant_id, horario_id]
          properties:
            tenant_id:
              type: string
            horario_id:
              type: string

        HorarioResponse:
          type: object
          properties:
            horario_id:
              type: string
            curso_id:
              type: string
            dias:
              type: array
              items:
                type: string
            inicio_hora:
              type: string
            fin_hora:
              type: string
            tenant_id:
              type: string

        ListarHorariosResponse:
          type: object
          properties:
            horarios:
              type: array
              items:
                $ref: "#/components/schemas/HorarioResponse"
            paginacion:
              type: object
              properties:
                total:
                  type: integer
                lastHorarioId:
                  type: string

resources:
  Resources:
    TablaHorario:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_horario
        AttributeDefinitions:
          - AttributeName: tenant_id_curso_id
            AttributeType: S
          - AttributeName: horario_id
            AttributeType: S
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_curso_id
            KeyType: HASH
          - AttributeName: horario_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_horario_index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: horario_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
