org: juanrodo
service: api-horario

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::735395269158:role/LabRole
  environment:
    FUNCION_ELIMINAR_COMPRAS: api-compras-${sls:stage}-eliminarCompra
    FUNCION_ACTUALIZAR_COMPRA: api-compras-${sls:stage}-actualizarCompras
    FUNCION_CURSO: api-curso-${sls:stage}-obtenerCurso
    TABLE_HORARIO: ${sls:stage}-t_horario
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

functions:
  crearHorario:
    handler: Lambda_CrearHorario.handler
    events:
      - http:
          path: /horario/crear
          method: post
          cors: true
          integration: lambda

  listarHorario:
    handler: Lambda_ListarHorario.handler
    events:
      - http:
          path: /horario/listar
          method: get
          cors: true
          integration: lambda

  obtenerHorario:
    handler: Lambda_BuscarHorario.handler
    events:
      - http:
          path: /horario/buscar
          method: get
          cors: true
          integration: lambda

  actualizarHorario:
    handler: Lambda_ModiHorario.handler
    events:
      - http:
          path: /horario/modificar
          method: put
          cors: true
          integration: lambda

  eliminarHorario:
    handler: Lambda_EliminarHorario.handler
    events:
      - http:
          path: /horario/eliminar
          method: delete
          cors: true
          integration: lambda

  doc:
    handler: Lambda_Doc.handler
    events:
      - http:
          path: /doc
          method: get
          cors: true
      - http:
          path: /doc/{proxy+}
          method: get
          cors: true

resources:
  Resources:
    TablaHorario:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_horario
        AttributeDefinitions:
          - AttributeName: tenant_id_curso_id
            AttributeType: S
          - AttributeName: horario_id
            AttributeType: S
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_curso_id
            KeyType: HASH
          - AttributeName: horario_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          - IndexName: tenant_horario_index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: horario_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  Outputs:
    TablaHorarioStreamArn:
      Description: ARN del Stream de la tabla de horarios
      Value:
        Fn::GetAtt:
          - TablaHorario
          - StreamArn
      Export:
        Name: ${self:service}-${sls:stage}-HorarioStreamArn

package:
  individually: false
  include:
    - '**'
