org: juanrodo
service: api-curso

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::674438223832:role/LabRole
  environment:
    TABLE_CURSO: ${sls:stage}-t_curso
    TABLE_USER: ${sls:stage}-t_horario
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar 

functions:
  crearHorario:
    handler: Lambda_CrearHorario.handler
    events:
      - http:
          path: /curso
          method: post
          cors: true

  listarHorario:
    handler: Lambda_ListarHorario.handler
    events:
      - http:
          path: /curso
          method: get
          cors: true

  obtenerHorario:
    handler: Lambda_BuscarHorario.handler
    events:
      - http:
          path: /curso/buscar
          method: get
          cors: true

  actualizarHorario:
    handler: Lambda_ModiHorario.handler
    events:
      - http:
          path: /curso/modificar
          method: put
          cors: true

  eliminarHorario:
    handler: Lambda_EliminarHorario.handler
    events:
      - http:
          path: /curso/eliminar
          method: delete
          cors: true

resources:
  Resources:
    TablaHorario:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_horario
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: horario_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: horario_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
