org: juanrodo
service: api-horario

plugins:
  - serverless-openapi-documentation

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 60
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    FUNCION_CURSO: api-curso-${sls:stage}-obtenerCurso
    TABLE_HORARIO: ${sls:stage}-t_horario
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

custom:
  documentation:
    version: 1.0.0
    title: API de Horarios
    description: Endpoints para gestionar los horarios de los cursos.
    models:
      - name: CrearHorarioRequest
        contentType: application/json
        schema:
          type: object
          required: [tenant_id, curso_id, dias, inicio_hora, fin_hora]
          properties:
            tenant_id: { type: string }
            curso_id: { type: string }
            dias:
              type: array
              items: { type: string }
            inicio_hora: { type: string, example: "08:00" }
            fin_hora: { type: string, example: "10:00" }

      - name: ActualizarHorarioRequest
        contentType: application/json
        schema:
          type: object
          required: [tenant_id, horario_id, dias, inicio_hora, fin_hora]
          properties:
            tenant_id: { type: string }
            horario_id: { type: string }
            dias:
              type: array
              items: { type: string }
            inicio_hora: { type: string, example: "09:00" }
            fin_hora: { type: string, example: "11:00" }

      - name: EliminarHorarioRequest
        contentType: application/json
        schema:
          type: object
          required: [tenant_id, horario_id]
          properties:
            tenant_id: { type: string }
            horario_id: { type: string }

      - name: HorarioResponse
        contentType: application/json
        schema:
          type: object
          properties:
            horario_id: { type: string }
            curso_id: { type: string }
            dias:
              type: array
              items: { type: string }
            inicio_hora: { type: string }
            fin_hora: { type: string }
            tenant_id: { type: string }

      - name: ListarHorariosResponse
        contentType: application/json
        schema:
          type: object
          properties:
            horarios:
              type: array
              items:
                $ref: '#/components/schemas/HorarioResponse'
            paginacion:
              type: object
              properties:
                total: { type: integer }
                lastHorarioId: { type: string }

functions:
  crearHorario:
    handler: Lambda_CrearHorario.handler
    events:
      - http:
          path: /horario/crear
          method: post
          cors: true
          documentation:
            summary: Crear horario
            description: Crea un horario para un curso dado.
            requestBody:
              required: true
            requestModels:
              'application/json': CrearHorarioRequest
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Horario creado exitosamente

  listarHorario:
    handler: Lambda_ListarHorario.handler
    events:
      - http:
          path: /horario/listar
          method: get
          cors: true
          documentation:
            summary: Listar horarios
            description: Lista todos los horarios disponibles.
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Lista de horarios
                responseModels:
                  'application/json': ListarHorariosResponse

  obtenerHorario:
    handler: Lambda_BuscarHorario.handler
    events:
      - http:
          path: /horario/buscar
          method: get
          cors: true
          documentation:
            summary: Obtener horario
            description: Devuelve los datos de un horario específico.
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Horario encontrado
                responseModels:
                  'application/json': HorarioResponse

  actualizarHorario:
    handler: Lambda_ModiHorario.handler
    events:
      - http:
          path: /horario/modificar
          method: put
          cors: true
          documentation:
            summary: Modificar horario
            description: Modifica los datos de un horario existente.
            requestBody:
              required: true
            requestModels:
              'application/json': ActualizarHorarioRequest
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Horario modificado

  eliminarHorario:
    handler: Lambda_EliminarHorario.handler
    events:
      - http:
          path: /horario/eliminar
          method: delete
          cors: true
          documentation:
            summary: Eliminar horario
            description: Elimina un horario específico.
            requestBody:
              required: true
            requestModels:
              'application/json': EliminarHorarioRequest
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Horario eliminado exitosamente

resources:
  Resources:
    TablaHorario:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_horario
        AttributeDefinitions:
          - AttributeName: tenant_id_curso_id
            AttributeType: S
          - AttributeName: horario_id
            AttributeType: S
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_curso_id
            KeyType: HASH
          - AttributeName: horario_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_horario_index
            KeySchema:
              - AttributeName: tenant_id
                KeyType: HASH
              - AttributeName: horario_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
