org: juanrodo
service: api-compras

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_COMPRAS: ${sls:stage}-t_compras
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar
    FUNCION_BUSCAR_CURSO: api-curso-${sls:stage}-obtenerCurso
    FUNCION_BUSCAR_HORARIO: api-horario-${sls:stage}-obtenerHorario

functions:
  comprarCurso:
    handler: Lambda_Comprar.handler
    events:
      - http:
          path: compra/comprar
          method: post
          cors: true

  listarCompras:
    handler: Lambda_ListarCompras.handler
    events:
      - http:
          path: compra/listar
          method: get
          cors: true

  eliminarCompra:
    handler: Lambda_EliminarCompra.handler
    events:
      - http:
          path: compra/eliminar
          method: delete
          cors: true

  doc:
    handler: lambda_Doc.lambda_handler
    events:
      - http:
          path: doc
          method: get
      - http:
          path: doc/{proxy+}
          method: get

package:
  individually: false
  include:
    - '**/*.js'
    - doc/**

resources:
  Resources:
    TablaCompras:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_compras
        AttributeDefinitions:
          - AttributeName: tenant_id_dni_estado
            AttributeType: S
          - AttributeName: curso_id
            AttributeType: S
          - AttributeName: tenant_id_curso_id
            AttributeType: S
          - AttributeName: alumno_dni
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id_dni_estado
            KeyType: HASH
          - AttributeName: curso_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_curso_index
            KeySchema:
              - AttributeName: tenant_id_curso_id
                KeyType: HASH
              - AttributeName: alumno_dni
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
