org: juanrodo
service: api-compras

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_CURSO: ${sls:stage}-t_curso
    TABLE_COMPRAS: ${sls:stage}-t_compras
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar
    FUNCION_BUSCAR_CURSO: api-curso-${sls:stage}-obtenerCurso
    FUNCION_BUSCAR_HORARIO: api-horario-${sls:stage}-obtenerHorario

functions:
  comprarcurso:
    handler: Lambda_Comprar.handler
    events:
      - http:
          path: /compra/comprar
          method: post
          cors: true

  listarCompras:
    handler: Lambda_ListarCompras.handler
    events:
      - http:
          path: /compra/listar
          method: get
          cors: true
package:
individually: false
include:
  - '**/*.js'
  
resources:
  Resources:
    TablaCompras:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_compras
        AttributeDefinitions:
          - AttributeName: tenant_id$curso_id
            AttributeType: S
          - AttributeName: dni$estado
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id$curso_id
            KeyType: HASH
          - AttributeName: dni$estado
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
