org: juanrodo
service: api-org

plugins:
  - serverless-openapi-documentation

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 60
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_ORG: ${sls:stage}-t_org
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

custom:
  documentation:
    version: 1.0.0
    title: API Organización
    description: Endpoints para gestionar organizaciones (tenants)
    models:
      - name: CrearOrganizacionRequest
        contentType: application/json
        schema:
          type: object
          required: [tenant_id, domain, descripcion, correo]
          properties:
            tenant_id:
              type: string
            domain:
              type: string
            descripcion:
              type: string
            correo:
              type: string

      - name: ModificarOrganizacionRequest
        contentType: application/json
        schema:
          type: object
          required: [tenant_id]
          properties:
            tenant_id:
              type: string
            domain:
              type: string
            descripcion:
              type: string
            correo:
              type: string

      - name: BuscarOrganizacionRequest
        contentType: application/json
        schema:
          type: object
          required: [tenant_id]
          properties:
            tenant_id:
              type: string

      - name: ListaOrganizacionesResponse
        contentType: application/json
        schema:
          type: object
          properties:
            organizaciones:
              type: array
              items:
                type: object
                properties:
                  tenant_id:
                    type: string
                  domain:
                    type: string
                  descripcion:
                    type: string
                  correo:
                    type: string
            total:
              type: integer

      - name: BuscarOrganizacionResponse
        contentType: application/json
        schema:
          type: object
          properties:
            tenant_id:
              type: string
            domain:
              type: string
            descripcion:
              type: string
            correo:
              type: string

      - name: RespuestaGenerica
        contentType: application/json
        schema:
          type: object
          properties:
            message:
              type: string
            error:
              type: string

functions:
  crearorg:
    handler: Lambda_CrearOrganizacion.lambda_handler
    events:
      - http:
          path: /org/crear
          method: post
          cors: true
          documentation:
            summary: Crear organización
            description: Crear una nueva organización (tenant).
            requestBody:
              description: Datos de la organización a crear
              required: true
            requestModels:
              'application/json': CrearOrganizacionRequest
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Organización creada exitosamente
                responseModels:
                  'application/json': RespuestaGenerica

  listarorg:
    handler: Lambda_ListarOrg.lambda_handler
    events:
      - http:
          path: /org/listar
          method: get
          cors: true
          documentation:
            summary: Listar organizaciones
            description: Lista todas las organizaciones registradas.
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Lista de organizaciones
                responseModels:
                  'application/json': ListaOrganizacionesResponse

  buscarorg:
    handler: Lambda_BuscarOrg.lambda_handler
    events:
      - http:
          path: /org/buscar
          method: post
          cors: true
          documentation:
            summary: Buscar organización
            description: Busca una organización por su tenant_id.
            requestBody:
              description: Datos de búsqueda
              required: true
            requestModels:
              'application/json': BuscarOrganizacionRequest
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Organización encontrada
                responseModels:
                  'application/json': BuscarOrganizacionResponse

  modificarorg:
    handler: Lambda_ModiOrg.lambda_handler
    events:
      - http:
          path: /org/modi
          method: put
          cors: true
          documentation:
            summary: Modificar organización
            description: Modifica los datos de una organización existente.
            requestBody:
              description: Datos para modificar una organización
              required: true
            requestModels:
              'application/json': ModificarOrganizacionRequest
            methodResponses:
              - statusCode: 200
                responseBody:
                  description: Organización modificada exitosamente
                responseModels:
                  'application/json': RespuestaGenerica

resources:
  Resources:
    TablaOrg:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_org
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
