org: juanrodo
service: api-org

plugins:
  - serverless-openapi-documenter

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 60
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_ORG: ${sls:stage}-t_org
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

functions:
  crearorg:
    handler: Lambda_CrearOrganizacion.lambda_handler
    events:
      - http:
          path: /org/crear
          method: post
          cors: true
          summary: Crear organización
          description: Crear una nueva organización (tenant).
          requestBody:
            description: Datos de la organización a crear.
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/CrearOrganizacionRequest'
          responses:
            '200':
              description: Organización creada exitosamente
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/RespuestaGenerica'

  listarorg:
    handler: Lambda_ListarOrg.lambda_handler
    events:
      - http:
          path: /org/listar
          method: get
          cors: true
          summary: Listar organizaciones
          description: Lista todas las organizaciones registradas.
          responses:
            '200':
              description: Lista de organizaciones
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ListaOrganizacionesResponse'

  buscarorg:
    handler: Lambda_BuscarOrg.lambda_handler
    events:
      - http:
          path: /org/buscar
          method: post
          cors: true
          summary: Buscar organización
          description: Busca una organización por su `tenant_id`.
          requestBody:
            description: Datos de búsqueda
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/BuscarOrganizacionRequest'
          responses:
            '200':
              description: Organización encontrada
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/BuscarOrganizacionResponse'

  modificarorg:
    handler: Lambda_ModiOrg.lambda_handler
    events:
      - http:
          path: /org/modi
          method: put
          cors: true
          summary: Modificar organización
          description: Modifica los datos de una organización existente.
          requestBody:
            description: Datos para modificar una organización.
            required: true
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/ModificarOrganizacionRequest'
          responses:
            '200':
              description: Organización modificada exitosamente
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/RespuestaGenerica'

custom:
  openapi:
    title: API Organización
    version: 1.0.0
    description: Endpoints para gestionar organizaciones (tenants)
    output: openapi.json
    format: json
    openApiVersion: 3.0.3
    postmanCollection: postman-org.json
    components:
      schemas:
        CrearOrganizacionRequest:
          type: object
          required: [tenant_id, domain, descripcion, correo]
          properties:
            tenant_id:
              type: string
              description: ID único de la organización
            domain:
              type: string
              description: Dominio asociado
            descripcion:
              type: string
              description: Descripción de la organización
            correo:
              type: string
              description: Correo de contacto

        ModificarOrganizacionRequest:
          type: object
          required: [tenant_id]
          properties:
            tenant_id:
              type: string
              description: ID de la organización a modificar
            domain:
              type: string
              description: Nuevo dominio
            descripcion:
              type: string
              description: Nueva descripción
            correo:
              type: string
              description: Nuevo correo

        BuscarOrganizacionRequest:
          type: object
          required: [tenant_id]
          properties:
            tenant_id:
              type: string
              description: ID de la organización a buscar

        BuscarOrganizacionResponse:
          type: object
          properties:
            tenant_id:
              type: string
            domain:
              type: string
            descripcion:
              type: string
            correo:
              type: string

        ListaOrganizacionesResponse:
          type: object
          properties:
            organizaciones:
              type: array
              items:
                type: object
                properties:
                  tenant_id:
                    type: string
                  domain:
                    type: string
                  descripcion:
                    type: string
                  correo:
                    type: string
            total:
              type: integer
              description: Total de organizaciones devueltas

        RespuestaGenerica:
          type: object
          properties:
            message:
              type: string
              description: Mensaje informativo
            error:
              type: string
              description: Mensaje de error, si aplica

resources:
  Resources:
    TablaOrg:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_org
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
