org: juanrodo
service: api-org

plugins:
  - serverless-auto-swagger

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 60
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_ORG: ${sls:stage}-t_org
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

functions:
  crearorg:
    handler: Lambda_CrearOrganizacion.lambda_handler
    events:
      - http:
          path: /org/crear
          method: post
          cors: true
          documentation:
            summary: Crear nueva organización (tenant)
            description: Registra una nueva organización educativa.
            tags:
              - Organización
            requestBody:
              description: Datos de la organización
              required: true
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/CrearOrganizacionRequest'
            responses:
              200:
                description: Organización creada exitosamente
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/RespuestaGenerica'

  listarorg:
    handler: Lambda_ListarOrg.lambda_handler
    events:
      - http:
          path: /org/listar
          method: get
          cors: true
          documentation:
            summary: Listar organizaciones
            description: Devuelve todas las organizaciones registradas.
            tags: [Organización]
            responses:
              200:
                description: Lista de organizaciones
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/ListaOrganizacionesResponse'

  buscarorg:
    handler: Lambda_BuscarOrg.lambda_handler
    events:
      - http:
          path: /org/buscar
          method: post
          cors: true
          documentation:
            summary: Buscar organización
            description: Busca una organización por su tenant_id.
            tags: [Organización]
            requestBody:
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/BuscarOrganizacionRequest'
            responses:
              200:
                description: Organización encontrada
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/BuscarOrganizacionResponse'

  modificarorg:
    handler: Lambda_ModiOrg.lambda_handler
    events:
      - http:
          path: /org/modi
          method: put
          cors: true
          documentation:
            summary: Modificar organización
            description: Modifica campos de una organización. Requiere token con rol admin.
            tags: [Organización]
            requestHeaders:
              - name: Authorization
                required: true
                description: Token JWT
            requestBody:
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/ModificarOrganizacionRequest'
            responses:
              200:
                description: Organización modificada
                content:
                  application/json:
                    schema:
                      $ref: '#/components/schemas/RespuestaGenerica'

custom:
  autoswagger:
    type: httpApi
    generateSwaggerOnDeploy: true
    apiType: http
    title: API Organización
    description: Endpoints de gestión de organizaciones (tenants)
    basePath: /dev
    swaggerPath: /swagger
    swaggerJsonPath: /swagger.json
    models:
      CrearOrganizacionRequest:
        type: object
        required: [tenant_id, domain, descripcion, correo]
        properties:
          tenant_id: { type: string }
          domain: { type: string }
          descripcion: { type: string }
          correo: { type: string }

      ModificarOrganizacionRequest:
        type: object
        required: [tenant_id]
        properties:
          tenant_id: { type: string }
          domain: { type: string }
          descripcion: { type: string }
          correo: { type: string }

      BuscarOrganizacionRequest:
        type: object
        required: [tenant_id]
        properties:
          tenant_id: { type: string }

      BuscarOrganizacionResponse:
        type: object
        properties:
          tenant_id: { type: string }
          domain: { type: string }
          descripcion: { type: string }
          correo: { type: string }

      ListaOrganizacionesResponse:
        type: object
        properties:
          organizaciones:
            type: array
            items:
              type: object
              properties:
                tenant_id: { type: string }
                domain: { type: string }
                descripcion: { type: string }
                correo: { type: string }
          total: { type: integer }

      RespuestaGenerica:
        type: object
        properties:
          message: { type: string }
          error: { type: string }

resources:
  Resources:
    TablaOrg:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_org
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

