org: juanrodo
service: api-org

provider:
  name: aws
  runtime: python3.12
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_ORG: ${sls:stage}-t_org
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar

functions:
  crearorg:
    handler: Lambda_CrearOrganizacion.lambda_handler
    events:
      - http:
          path: /org/crear
          method: post
          cors: true

  listarorg:
    handler: Lambda_ListarOrg.lambda_handler
    events:
      - http:
          path: /org/listar
          method: get
          cors: true

  buscarorg:
    handler: Lambda_BuscarOrg.lambda_handler
    events:
      - http:
          path: /org/buscar
          method: post
          cors: true

  modificarorg:
    handler: Lambda_ModiOrg.lambda_handler
    events:
      - http:
          path: /org/modi
          method: put
          cors: true
  doc:
    handler: Lambda_Doc.handler
    events:
      - http:
          path: /doc
          method: get
          cors: true
      - http:
          path: /doc/{proxy+}
          method: get
          cors: true

resources:
  Resources:
    TablaOrg:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_org
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
