org: juanrodo
service: api-curso

plugins:
  - serverless-auto-swagger

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 60
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_CURSO: ${sls:stage}-t_curso
    TABLE_USER: ${sls:stage}-t_usuario
    TABLE_HORARIO: ${sls:stage}-t_horario
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar
    FUNCION_ELIMINAR_HORARIO: api-horario-${sls:stage}-eliminarHorario

functions:
  crearCurso:
    handler: Lambda_CrearCurso.handler
    events:
      - http:
          path: /curso/crear
          method: post
          cors: true

  listarCursos:
    handler: Lambda_ListarCursos.handler
    events:
      - http:
          path: /curso/listar
          method: get
          cors: true

  obtenerCurso:
    handler: Lambda_BuscarCurso.handler
    events:
      - http:
          path: /curso/buscar
          method: get
          cors: true

  actualizarCurso:
    handler: Lambda_ModiCurso.handler
    events:
      - http:
          path: /curso/modificar
          method: put
          cors: true

  eliminarCurso:
    handler: Lambda_EliminarCurso.handler
    events:
      - http:
          path: /curso/eliminar
          method: delete
          cors: true

package:
  individually: false
  include:
    - '**/*.js'

resources:
  Resources:
    TablaCursos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_curso
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: curso_id
            AttributeType: S
          - AttributeName: tenant_instructor
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: curso_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: tenant_instructor_index
            KeySchema:
              - AttributeName: tenant_instructor
                KeyType: HASH
              - AttributeName: curso_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

custom:
  autoswagger:
    type: httpApi
    generateSwaggerOnDeploy: true
    title: API de Cursos
    description: Endpoints para crear, listar, modificar y eliminar cursos en un tenant educativo.
    basePath: /${sls:stage}
    useStage: true
    swaggerPath: /swagger
    swaggerJsonPath: /swagger.json
    models:
      CrearCursoRequest:
        type: object
        required: [tenant_id, nombre, descripcion, inicio, fin, precio]
        properties:
          tenant_id: { type: string }
          nombre: { type: string }
          descripcion: { type: string }
          inicio: { type: string, format: date }
          fin: { type: string, format: date }
          precio: { type: number }

      CursoResponse:
        type: object
        properties:
          curso_id: { type: string }
          nombre: { type: string }
          descripcion: { type: string }
          inicio: { type: string, format: date }
          fin: { type: string, format: date }
          precio: { type: number }
          instructor_dni: { type: string }
          instructor_nombre: { type: string }
          tenant_id: { type: string }

      ListarCursosResponse:
        type: object
        properties:
          cursos:
            type: array
            items:
              $ref: "#/components/schemas/CursoResponse"
          paginacion:
            type: object
            properties:
              ultimoCursoId: { type: string }
              total: { type: integer }

      ActualizarCursoRequest:
        type: object
        properties:
          nombre: { type: string }
          descripcion: { type: string }
          inicio: { type: string, format: date }
          fin: { type: string, format: date }
          precio: { type: number }

      ActualizarCursoResponse:
        type: object
        properties:
          message: { type: string }
          curso_id: { type: string }
          actualizaciones:
            type: object
            additionalProperties: true

      EliminarCursoRequest:
        type: object
        required: [tenant_id, curso_id]
        properties:
          tenant_id: { type: string }
          curso_id: { type: string }

      EliminarCursoResponse:
        type: object
        properties:
          message: { type: string }
          curso_id: { type: string }
          total_horarios: { type: integer }
