org: juanrodo
service: api-curso

provider:
  name: aws
  runtime: nodejs22.x
  memorySize: 1024
  timeout: 30
  iam:
    role: arn:aws:iam::752087942362:role/LabRole
  environment:
    TABLE_CURSO: ${sls:stage}-t_curso
    TABLE_USER: ${sls:stage}-t_usuario
    TABLE_HORARIO: ${sls:stage}-t_horario
    FUNCION_VALIDAR: api-usuario-${sls:stage}-validar
    FUNCION_ELIMINAR_HORARIO: api-horario-${sls:stage}-eliminarHorario
    FUNCION_ACTUALIZAR_COMPRA: api-compras-${sls:stage}-actualizarCompras

functions:
  crearCurso:
    handler: Lambda_CrearCurso.handler
    events:
      - http:
          path: /curso/crear
          method: post
          cors: true
          integration: lambda

  listarCursos:
    handler: Lambda_ListarCursos.handler
    events:
      - http:
          path: /curso/listar
          method: get
          cors: true
          integration: lambda

  obtenerCurso:
    handler: Lambda_BuscarCurso.handler
    events:
      - http:
          path: /curso/buscar
          method: get
          cors: true
          integration: lambda

  actualizarCurso:
    handler: Lambda_ModiCurso.handler
    events:
      - http:
          path: /curso/modificar
          method: put
          cors: true
          integration: lambda

  eliminarCurso:
    handler: Lambda_EliminarCurso.handler
    events:
      - http:
          path: /curso/eliminar
          method: delete
          cors: true
          integration: lambda

  doc:
    handler: Lambda_Doc.handler
    events:
      - http:
          path: doc
          method: get
          cors: true
      - http:
          path: doc/{proxy+}
          method: get
          cors: true

resources:
  Resources:
    TablaCursos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${sls:stage}-t_curso
        AttributeDefinitions:
          - AttributeName: tenant_id
            AttributeType: S
          - AttributeName: curso_id
            AttributeType: S
          - AttributeName: tenant_instructor
            AttributeType: S
        KeySchema:
          - AttributeName: tenant_id
            KeyType: HASH
          - AttributeName: curso_id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
        GlobalSecondaryIndexes:
          - IndexName: tenant_instructor_index
            KeySchema:
              - AttributeName: tenant_instructor
                KeyType: HASH
              - AttributeName: curso_id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

  Outputs:
    TablaCursosStreamArn:
      Description: ARN del Stream de la tabla de cursos
      Value:
        Fn::GetAtt:
          - TablaCursos
          - StreamArn
      Export:
        Name: ${self:service}-${sls:stage}-CursoStreamArn

package:
  individually: false
  include:
    - '**'
